### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by octo-kumo** [KurozeroPB/al-api#19]
Why, why did you made it a paid service?
It is reasonably easy to make our own query machine, so this is not worth the money.
I appreciate your work, but $2 a month for just a a simple api like this is unreasonable.

For anyone that is trying to make one like this, the method I found to be the best is fetch
"<link>" and parse the textfield's text. However that do not include the skins, so if you want the skins, request "<link>".
The parsing can be found inside <link>

Sorry for not wanting to support you.

**Comment by Pepijn98** [comment]
I do not care if someone thinks is worth paying, it takes a reasonable amount of time to maintain especially if the wiki changes and things crash. Also if I ever want to move on from using heroku to a better payed service I need to get the money from somewhere, it doesn't magically grow on trees. If you don't thinks it's worth paying for then I don't want you to use it in the first place.
