### ISSUE TITLE
Add chibi images

### ISSUE THREAD

**Issue by piggylux** [KurozeroPB/al-api#6]
Is it possible to get the chibi images from ships too ?

**Comment by Pepijn98** [comment]
I don't think the wiki provides those images, I've not seen them.
If they do then it could be possible, if they don't then it's not possible.

**Comment by piggylux** [comment]
It's available in the html source code though

**Comment by Pepijn98** [comment]
Oh, well then it's not a problem, I'll add it in soon.

**Comment by Pepijn98** [comment]
Added `chibi` property to the api response

**Comment by piggylux** [comment]
Thank you I love you
