### ISSUE TITLE
API requesting has become stricter

### ISSUE THREAD

**Issue by piggylux** [KurozeroPB/al-api#7]
Issue on some requests:
- Jeanne d'Arc (https://azurlane.koumakan.jp/Jeanne_d%27Arc) can no longer be requested. I could get her by requesting `jeanne` or `jeanne d'arc` etc... but now it's impossible to get her.
- Similar issue for Jean Bart (https://azurlane.koumakan.jp/Jean_Bart) when it was possible to simply request `jean` instead of her full name.

I don't know if other ships are affected.

**Comment by Pepijn98** [comment]
`jean` is not a valid ship name and never has been, `jeanne` works because I specifically check for her name because it works weird when trying to uppercase names. Both giving a 500 internal server right now is my fault for not properly testing, should be fixed soon.

**Comment by piggylux** [comment]
Right for jean bart, I spoke too fast

**Comment by Pepijn98** [comment]
It's okay, should be fixed now

**Comment by piggylux** [comment]
Yes I can confirm, thank you~
